---

- name: Install Mysql server
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: Update mysql root password for all root accounts
  mysql_user: name=root check_implicit_admin=yes login_user=root login_password={{ db.root.password }} host={{ db.root.host }} password={{ db.root.password }}

- name: Create .my.cnf for root
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ db.root.password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"

- name: Remove the test database
  mysql_db: name=test state=absent
